<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>1612745 - Run all test cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>81228898-9bfa-4794-9dee-d031ae8d653c</testSuiteGuid>
   <testCaseLink>
      <guid>c18fbc40-6818-47c0-b0af-d5147f57bf39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/1612745/1612745 - Test sign in</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9745f65b-59d3-4117-93cf-a0a2a5e35dd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>406a237d-3de8-4ced-a9cc-75c3564c1180</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b404d41-cae7-4926-a305-dbeed6884aa0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/1612745/1612745 - Test sign up</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48e2f6ce-8cab-4625-94af-057cfff8a5e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f45c6455-1f7d-4c11-b489-17eb51d73b7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b723d25b-3bdf-4f7d-997d-d82bb2260b0e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
